AWSTemplateFormatVersion: "2010-09-09"

Description: Website S3 & CloudFront Distribution

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource:
              - !Sub "${WebsiteBucket.Arn}/*"

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName:
              !Select [2, !Split ["/", !GetAtt WebsiteBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only # S3 buckets with website hosting don't support HTTPS
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true # Use default CloudFront certificate (or specify an ACM certificate)
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https # Redirect HTTP to HTTPS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

Outputs:
  S3BucketName:
    Value: !Ref WebsiteBucket
    Description: The name of the S3 bucket for the website.
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL of the website hosted on S3 bucket
  WebsiteBucketARN:
    Value: !GetAtt WebsiteBucket.Arn
    Description: S3 bucket Arn
  DistributionDomainName:
    Value: !GetAtt WebsiteDistribution.DomainName
    Description: The domain name of the CloudFront distribution
